name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pyarrow=2.0
  - pandas-profiling
  - pyarrow=2.0
  - pydantic=1.8.2
  - pip:
      - wandb
  
